### ISSUE TITLE
forms and lists

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/infrastructure#18]
currently, we are using an old version of gravity forms to manage a few forms that are filled by the LGM participants.

gravity forms is not "really free" and does not perfectly match our needs, so we are considering to replace it.

the discussion on a replacement for it started in #6 and three plugins have already been mentioned:
- https://github.com/ms-studio/minimalistic-event-manager
- User Submitted Posts  
  http://wordpress.org/plugins/user-submitted-posts/
- Frontend Uploader
http://wordpress.org/plugins/frontend-uploader/

the first step should be to define for what we are using gravity forms (and eventually detect more potential uses):
- registration list
- talks submission
- ask for reimbursement
- upload the talks' slides

who has been creating/tweaking the forms:
- louis (needs a GUI way... or at least a straight forward one)
- femke (similar needs as louis)
- ale (any comfortable way)

what is being done with the forms and lists:
- creating a form, mostly by importing the previous year's one
- let unauthenticated visitors submit entries
- see a list of submissions in wordpress
- edit the values in wordpress
- download a list of submissions as csv
- use the content of the list and display it on the site through a template

it's also important to recall that a few people refused to look and edit the entries in wordpress, because "they don't do the website".

now, it's up to us to play with all those variable and produce a solution that makes our users happy!

**Comment by ms-studio** [comment]
So, we kept working with Formidable Pro... closing the issue for now.
