### ISSUE TITLE
setup a new web server

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/infrastructure#25]
switching to a new server has been proposed to the mailing list.

the tasks are not definitive yet, and will evolve according to the discussion on the ML.

- [ ] check that tux family fits our needs
      - [ ] php version
      - [ ] mod rewrite
      - [ ] curl
- [ ] create a tux family account for the LGM
  - [x] ale has created his account
  - [x] lgm project created
  - [x] lgm project validated by tux family
  - [x] install the lgm/ wp
  - [ ] install a test lgm2014 wp and check that the home made scripts work correctly
  - [ ] check that curl works correctly
- [x] copy the old sites to the new server, as static html
- [ ] make a backup of the data and database of each old site and document where it is stored and how it can be retrieved.
- [x] create  a new wordpress instance for lgm/ and 2015/
- [x] switch the DNS to the new server
  - [x] before switching the DNS, change the "WordPress address URL" and  "Site address (URL)" (cf. http://codex.wordpress.org/Giving_WordPress_Its_Own_Directory)
- [ ] create email forwardings for those who wants to have them
- [ ] switch off the old server (we probably don't want to do it before the next lgm)

**Comment by ms-studio** [comment]
I assume we can finally close this ticket :)
