### ISSUE TITLE
try to take over the twitter.com/LGMLeipzig account and rename to LGMeeting

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/infrastructure#3]
as requested by julien (and ginger).

a fast check suggest that the account might be in the hands of sirko.

**Comment by ms-studio** [comment]
What's the current status on this? It looks like the LGMLeipzig account has been shut down, so I assume the issue can be closed...

**Comment by xuv** [comment]
Ha tiens. C'est neuf ça. Le compte était encore présent le mois passé. Dommage que ça se termine comme ça.

**Comment by ms-studio** [comment]
En effet, dommage. Si on envisage d'utiliser twitter plus intensivement pour 2016, on pourrait songer à mettre en place un archivage automatique : 

https://github.com/ozh/ozh-tweet-archive-theme
+ http://code.tutsplus.com/tutorials/import-and-archive-your-tweets-with-wordpress--cms-22656
