### ISSUE TITLE
Give an icon (LGM logo) to the libregraphicsmeeting github account!

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/infrastructure#38]
We need an icon, so it's immediately recognizable on the github profiles of contributors!

:-)

**Comment by ms-studio** [comment]
@aoloe : bumping the issue :)

**Comment by aoloe** [comment]
it's done!
or you prefer one without text?

**Comment by ms-studio** [comment]
Perfect! With text looks good to me.
