### ISSUE TITLE
find a free alternative for rebelmouse

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/infrastructure#39]
we should find a free alternative to rebelmouse.

https://www.rebelmouse.com/LibreGraphicsMeeting/

**Comment by aoloe** [comment]
i didn't have a look at the rebelmouse functionality, but depending on what it does we could try to replace it with the code behind http://impagina.org/planet/ (transformed in a wp plugin)

**Comment by ms-studio** [comment]
Closing issue, as discussion has moved to https://github.com/libregraphicsmeeting/htdocs-2015/issues/15
