### ISSUE TITLE
Update Flickr Group Description

### ISSUE THREAD

**Issue by xuv** [libregraphicsmeeting/infrastructure#40]
Hello

Flickr Group description shows all the LGM up to the one in Madrid. This is really nice and would be cooler if it could link also the Leipzig and Toronto one.
https://www.flickr.com/groups/libregfx/

**Comment by ms-studio** [comment]
Well spotted – just completed the list.
Also I switched the header photo to a cooler one :))

**Comment by xuv** [comment]
:+1: :

**Comment by aoloe** [comment]
what would be a better heading?

~~~
See you soon in Toronto, 29 April - 2 May 2015!
libregraphicsmeeting.org/2015/
~~~

sounds a bit outdated...

~~~
See you in London in April 2016
libregraphicsmeeting.org
~~~

or a reference to the latest in toronto without the see you?

**Comment by ms-studio** [comment]
Done!
