### ISSUE TITLE
Verify website for Youtube

### ISSUE THREAD

**Issue by xuv** [libregraphicsmeeting/infrastructure#43]
Hey

This could be a quick one. But while reviewing our Youtube channel, I bumped into this request from Youtube. [The LGM website need to be verified in order to display the url on the page. ](https://www.google.com/webmasters/verification/verification?siteUrl=http://libregraphicsmeeting.org/&pli=1) Basically, verifying the website is as simple as dropping an file with a special name and clicking 'ok' afterwards in a form. If anyone has ftp or ssh access to the server. This could be done in a second. 
Verify form is here: https://www.google.com/webmasters/verification/verification?siteUrl=http://libregraphicsmeeting.org/&pli=1

**Comment by aoloe** [comment]
yep, my clients always tell me that things can be done in seconds :-)

i'll put it on my todo list!

**Comment by xuv** [comment]
@aoloe: Sorry ale. Didn't not want to sound rude. Indeed, whenever you have the time. I also thought you were a bunch with server access, not just you. Hope you're good.

**Comment by aoloe** [comment]
@xuv don't be sorry, it was more funny than rude... (most of all because i had such a discussion with a client not so long ago...)

and if i was currently actively maintaining the server the whole process would be a bit faster... right now i have to first copy the keys on the new laptop.

and i think that we are currently two with access to the server...

**Comment by patdavid** [comment]
Is there something I can do to help?

**Comment by ms-studio** [comment]
Actually the site _is_ already verified, using Google Webmaster tools (with HTML file upload method). And I just managed to get the linking between the URL and the youtube page to be approved. Let me know your google email addresses if you want access to the Google Webmaster Tools.

**Comment by aoloe** [comment]
nice thanks

**Comment by xuv** [comment]
Thanks all :) Btw, just fyi, I did a little polishing of the Youtube channel. Completed the different playlists from the past years and created the ones that were missing. That's about it.
