### ISSUE TITLE
archive the 2015, 2016 and 2017 websites

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/infrastructure#48]
- create one `htdocs-20xx-static` repository for each website
- check that everything is documented in the `htdocs-20xx`'s README.md file (plugins used, ...)
- create the html static pages
- remove wordpress
- upload the static files

- [x] 2015
- [x] 2016
- [ ] 2017
- [ ] 2018

**Comment by ms-studio** [comment]
I just created the static versions of the 2017, 2018 and 2019 websites.

I uploaded them to Github. I don't think I have write-access to the files on the server, to delete the WP instances.

**Comment by aoloe** [comment]
thanks @ms-studio

i've created a local backup of the wordpress sites and downloaded and deployed your static version to the server.

**Comment by ms-studio** [comment]
Great! This allowed me to fix the wordpress update issue on the /lgm site.
